version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(gomod)"
    labels:
      - "dependencies"
      - "patch"
    groups:
      gomod-updates:
        update-types:
          - minor
          - patch
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(github-actions)"
    labels:
      - "dependencies"
      - "patch"
    groups:
      action-updates:
        update-types:
          - minor
          - patch
