// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// IntegrationExtractValueRequest integration extract value request
//
// swagger:model IntegrationExtractValueRequest
type IntegrationExtractValueRequest struct {

	// body data type
	// Enum: ["json","xml","string"]
	BodyDataType string `json:"body_data_type,omitempty"`

	// key
	// Example: key
	Key string `json:"key,omitempty"`

	// name
	// Example: deploy
	Name string `json:"name,omitempty"`

	// value source
	// Enum: ["body","header"]
	ValueSource string `json:"value_source,omitempty"`

	// variable
	// Example: variable
	Variable string `json:"variable,omitempty"`
}

// Validate validates this integration extract value request
func (m *IntegrationExtractValueRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBodyDataType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateValueSource(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var integrationExtractValueRequestTypeBodyDataTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["json","xml","string"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		integrationExtractValueRequestTypeBodyDataTypePropEnum = append(integrationExtractValueRequestTypeBodyDataTypePropEnum, v)
	}
}

const (

	// IntegrationExtractValueRequestBodyDataTypeJSON captures enum value "json"
	IntegrationExtractValueRequestBodyDataTypeJSON string = "json"

	// IntegrationExtractValueRequestBodyDataTypeXML captures enum value "xml"
	IntegrationExtractValueRequestBodyDataTypeXML string = "xml"

	// IntegrationExtractValueRequestBodyDataTypeString captures enum value "string"
	IntegrationExtractValueRequestBodyDataTypeString string = "string"
)

// prop value enum
func (m *IntegrationExtractValueRequest) validateBodyDataTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, integrationExtractValueRequestTypeBodyDataTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *IntegrationExtractValueRequest) validateBodyDataType(formats strfmt.Registry) error {
	if swag.IsZero(m.BodyDataType) { // not required
		return nil
	}

	// value enum
	if err := m.validateBodyDataTypeEnum("body_data_type", "body", m.BodyDataType); err != nil {
		return err
	}

	return nil
}

var integrationExtractValueRequestTypeValueSourcePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["body","header"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		integrationExtractValueRequestTypeValueSourcePropEnum = append(integrationExtractValueRequestTypeValueSourcePropEnum, v)
	}
}

const (

	// IntegrationExtractValueRequestValueSourceBody captures enum value "body"
	IntegrationExtractValueRequestValueSourceBody string = "body"

	// IntegrationExtractValueRequestValueSourceHeader captures enum value "header"
	IntegrationExtractValueRequestValueSourceHeader string = "header"
)

// prop value enum
func (m *IntegrationExtractValueRequest) validateValueSourceEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, integrationExtractValueRequestTypeValueSourcePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *IntegrationExtractValueRequest) validateValueSource(formats strfmt.Registry) error {
	if swag.IsZero(m.ValueSource) { // not required
		return nil
	}

	// value enum
	if err := m.validateValueSourceEnum("value_source", "body", m.ValueSource); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this integration extract value request based on context it is used
func (m *IntegrationExtractValueRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *IntegrationExtractValueRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IntegrationExtractValueRequest) UnmarshalBinary(b []byte) error {
	var res IntegrationExtractValueRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
