// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ScheduleRequest schedule request
//
// swagger:model ScheduleRequest
type ScheduleRequest struct {

	// active
	Active bool `json:"active,omitempty"`

	// cron format
	// Example: * * * 1 *
	CronFormat string `json:"cron_format,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// project id
	ProjectID int64 `json:"project_id,omitempty"`

	// template id
	TemplateID int64 `json:"template_id,omitempty"`
}

// Validate validates this schedule request
func (m *ScheduleRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this schedule request based on context it is used
func (m *ScheduleRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ScheduleRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ScheduleRequest) UnmarshalBinary(b []byte) error {
	var res ScheduleRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
