// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Task task
//
// swagger:model Task
type Task struct {

	// debug
	Debug bool `json:"debug,omitempty"`

	// environment
	Environment string `json:"environment,omitempty"`

	// git branch
	GitBranch string `json:"git_branch,omitempty"`

	// id
	// Example: 23
	ID int64 `json:"id,omitempty"`

	// limit
	Limit string `json:"limit,omitempty"`

	// playbook
	Playbook string `json:"playbook,omitempty"`

	// secret
	Secret string `json:"secret,omitempty"`

	// status
	Status string `json:"status,omitempty"`

	// template id
	TemplateID int64 `json:"template_id,omitempty"`
}

// Validate validates this task
func (m *Task) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this task based on context it is used
func (m *Task) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Task) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Task) UnmarshalBinary(b []byte) error {
	var res Task
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
