// Code generated by go-swagger; DO NOT EDIT.

package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PostProjectProjectIDKeysReader is a Reader for the PostProjectProjectIDKeys structure.
type PostProjectProjectIDKeysReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostProjectProjectIDKeysReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewPostProjectProjectIDKeysNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostProjectProjectIDKeysBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /project/{project_id}/keys] PostProjectProjectIDKeys", response, response.Code())
	}
}

// NewPostProjectProjectIDKeysNoContent creates a PostProjectProjectIDKeysNoContent with default headers values
func NewPostProjectProjectIDKeysNoContent() *PostProjectProjectIDKeysNoContent {
	return &PostProjectProjectIDKeysNoContent{}
}

/*
PostProjectProjectIDKeysNoContent describes a response with status code 204, with default header values.

Access Key created
*/
type PostProjectProjectIDKeysNoContent struct {
}

// IsSuccess returns true when this post project project Id keys no content response has a 2xx status code
func (o *PostProjectProjectIDKeysNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post project project Id keys no content response has a 3xx status code
func (o *PostProjectProjectIDKeysNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post project project Id keys no content response has a 4xx status code
func (o *PostProjectProjectIDKeysNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this post project project Id keys no content response has a 5xx status code
func (o *PostProjectProjectIDKeysNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this post project project Id keys no content response a status code equal to that given
func (o *PostProjectProjectIDKeysNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the post project project Id keys no content response
func (o *PostProjectProjectIDKeysNoContent) Code() int {
	return 204
}

func (o *PostProjectProjectIDKeysNoContent) Error() string {
	return fmt.Sprintf("[POST /project/{project_id}/keys][%d] postProjectProjectIdKeysNoContent", 204)
}

func (o *PostProjectProjectIDKeysNoContent) String() string {
	return fmt.Sprintf("[POST /project/{project_id}/keys][%d] postProjectProjectIdKeysNoContent", 204)
}

func (o *PostProjectProjectIDKeysNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostProjectProjectIDKeysBadRequest creates a PostProjectProjectIDKeysBadRequest with default headers values
func NewPostProjectProjectIDKeysBadRequest() *PostProjectProjectIDKeysBadRequest {
	return &PostProjectProjectIDKeysBadRequest{}
}

/*
PostProjectProjectIDKeysBadRequest describes a response with status code 400, with default header values.

Bad type
*/
type PostProjectProjectIDKeysBadRequest struct {
}

// IsSuccess returns true when this post project project Id keys bad request response has a 2xx status code
func (o *PostProjectProjectIDKeysBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post project project Id keys bad request response has a 3xx status code
func (o *PostProjectProjectIDKeysBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post project project Id keys bad request response has a 4xx status code
func (o *PostProjectProjectIDKeysBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post project project Id keys bad request response has a 5xx status code
func (o *PostProjectProjectIDKeysBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post project project Id keys bad request response a status code equal to that given
func (o *PostProjectProjectIDKeysBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post project project Id keys bad request response
func (o *PostProjectProjectIDKeysBadRequest) Code() int {
	return 400
}

func (o *PostProjectProjectIDKeysBadRequest) Error() string {
	return fmt.Sprintf("[POST /project/{project_id}/keys][%d] postProjectProjectIdKeysBadRequest", 400)
}

func (o *PostProjectProjectIDKeysBadRequest) String() string {
	return fmt.Sprintf("[POST /project/{project_id}/keys][%d] postProjectProjectIdKeysBadRequest", 400)
}

func (o *PostProjectProjectIDKeysBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
