// Code generated by go-swagger; DO NOT EDIT.

package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PostProjectProjectIDRepositoriesReader is a Reader for the PostProjectProjectIDRepositories structure.
type PostProjectProjectIDRepositoriesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostProjectProjectIDRepositoriesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewPostProjectProjectIDRepositoriesNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /project/{project_id}/repositories] PostProjectProjectIDRepositories", response, response.Code())
	}
}

// NewPostProjectProjectIDRepositoriesNoContent creates a PostProjectProjectIDRepositoriesNoContent with default headers values
func NewPostProjectProjectIDRepositoriesNoContent() *PostProjectProjectIDRepositoriesNoContent {
	return &PostProjectProjectIDRepositoriesNoContent{}
}

/*
PostProjectProjectIDRepositoriesNoContent describes a response with status code 204, with default header values.

Repository created
*/
type PostProjectProjectIDRepositoriesNoContent struct {
}

// IsSuccess returns true when this post project project Id repositories no content response has a 2xx status code
func (o *PostProjectProjectIDRepositoriesNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post project project Id repositories no content response has a 3xx status code
func (o *PostProjectProjectIDRepositoriesNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post project project Id repositories no content response has a 4xx status code
func (o *PostProjectProjectIDRepositoriesNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this post project project Id repositories no content response has a 5xx status code
func (o *PostProjectProjectIDRepositoriesNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this post project project Id repositories no content response a status code equal to that given
func (o *PostProjectProjectIDRepositoriesNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the post project project Id repositories no content response
func (o *PostProjectProjectIDRepositoriesNoContent) Code() int {
	return 204
}

func (o *PostProjectProjectIDRepositoriesNoContent) Error() string {
	return fmt.Sprintf("[POST /project/{project_id}/repositories][%d] postProjectProjectIdRepositoriesNoContent", 204)
}

func (o *PostProjectProjectIDRepositoriesNoContent) String() string {
	return fmt.Sprintf("[POST /project/{project_id}/repositories][%d] postProjectProjectIdRepositoriesNoContent", 204)
}

func (o *PostProjectProjectIDRepositoriesNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
