// Code generated by go-swagger; DO NOT EDIT.

package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PostProjectProjectIDEnvironmentReader is a Reader for the PostProjectProjectIDEnvironment structure.
type PostProjectProjectIDEnvironmentReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostProjectProjectIDEnvironmentReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewPostProjectProjectIDEnvironmentNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /project/{project_id}/environment] PostProjectProjectIDEnvironment", response, response.Code())
	}
}

// NewPostProjectProjectIDEnvironmentNoContent creates a PostProjectProjectIDEnvironmentNoContent with default headers values
func NewPostProjectProjectIDEnvironmentNoContent() *PostProjectProjectIDEnvironmentNoContent {
	return &PostProjectProjectIDEnvironmentNoContent{}
}

/*
PostProjectProjectIDEnvironmentNoContent describes a response with status code 204, with default header values.

Environment created
*/
type PostProjectProjectIDEnvironmentNoContent struct {
}

// IsSuccess returns true when this post project project Id environment no content response has a 2xx status code
func (o *PostProjectProjectIDEnvironmentNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post project project Id environment no content response has a 3xx status code
func (o *PostProjectProjectIDEnvironmentNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post project project Id environment no content response has a 4xx status code
func (o *PostProjectProjectIDEnvironmentNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this post project project Id environment no content response has a 5xx status code
func (o *PostProjectProjectIDEnvironmentNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this post project project Id environment no content response a status code equal to that given
func (o *PostProjectProjectIDEnvironmentNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the post project project Id environment no content response
func (o *PostProjectProjectIDEnvironmentNoContent) Code() int {
	return 204
}

func (o *PostProjectProjectIDEnvironmentNoContent) Error() string {
	return fmt.Sprintf("[POST /project/{project_id}/environment][%d] postProjectProjectIdEnvironmentNoContent", 204)
}

func (o *PostProjectProjectIDEnvironmentNoContent) String() string {
	return fmt.Sprintf("[POST /project/{project_id}/environment][%d] postProjectProjectIdEnvironmentNoContent", 204)
}

func (o *PostProjectProjectIDEnvironmentNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
