name: Label Checker

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled
      - edited

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  check_semver_labels:
    name: Check Semver labels
    if: github.base_ref == 'main'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      checks: write
    steps:
      - name: Check for Semver labels
        uses: danielchabr/pr-labels-checker@v3.3
        with:
          hasSome: major,minor,patch
          githubToken: ${{ secrets.GITHUB_TOKEN }}

  check_cc_labels:
    name: Check conventional commits labels
    if: github.base_ref == 'main'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      checks: write
    steps:
      - uses: danielchabr/pr-labels-checker@v3.3
        with:
          hasSome: feature,enhancement,fix,bug,changed,deprecated,removed,security,docs,documentation,deps,dependencies,chore
          githubToken: ${{ secrets.GITHUB_TOKEN }}

  title-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5.5.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
